env: "local"
storage_path: "mongodb://root:example@mongo:27017"
database: "NoteVault"
collections:
  notes: "notes"
  notebooks: "notebooks"
  tags: "tags"
http_server:
  address: "0.0.0.0:8085"
  timeout: 5s
  idle_timeout: 60s